bankingproject/bankingapp/urls.py
from datetime import datetime

from django.urls import path
from . import views
from django.contrib.auth import views as auth_views, forms

app_name='bankingapp'
urlpatterns=[
    path('',views.home, name='home'),
    path('login/',views.login, name='login'),
    path('register/',views.register,name='register'),
    path('welcome/',views.welcome,name='welcome'),
    path('form/',views.form,name='form'),
]

bankingproject/bankingproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankingapp.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

bankingproject/bankingapp/models.py
from django.db import models

# Create your models here.

bankingproject/bankingapp/forms.py
# from django import forms
# from django.core.validators import RegexValidator
#
# GENDER_CHOICES = (
#         (1, ('Male')),
#         (2, ('Female')),
#     )
# MRL_CHOICES = (
# (1, 'Debit Card'),
# (2, 'Credit Card'),
# (3, 'Cheque Book'),)
# class Valueform(forms.Form):
#     name = forms.CharField(max_length = 100)
#     gender = forms.ModelMultipleChoiceField(
#                                       choices = GENDER_CHOICES,
#                                       widget  = forms.CheckboxSelectMultiple(),
#                                       label   = 'Search')
#     phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$', message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
#     phone = forms.CharField(validators=[phone_regex], max_length=17)
#     district = forms.ChoiceField(choices = (('1','Trivandrum'),('2','Kollam'),('3','Pathanamthitta'),('4','Alappuzha'),('5','Kottayam'),
#                                           ('6','Idukki'),('7','Ernakulam'),('8','Thrissur'),('9','Palakkad'),('10','Malappuram'),('11','Kozhikkode'),
#                                           ('12','Wayanad'),('13','Kannur'),('14','Kasargod')))
#     branches = forms.ChoiceField(choices = (('1','Padmanabhapuram'),('2','Shanmugham'),('3','Krishnapuram'),('4','Thangasheri'),('5','Adoor'),
#                                           ('6','Cherthala'),('7','Munnar'),('8','Aluva'),('9','Edappally'),('10','Guruvayur'),('11','Tirur'),
#                                           ('12','Manjeri'),('13','Mananchira'),('14','Thamarasseri'),('14','Kalpetta'),('14','Mananthavady')
#                                         ,('14','Thalassery'),('14','Koothuparamba'),('14','Manjesuaram')))
#     account_type= forms.ChoiceField(choices = (('1','Saving'),('2','Current'),('3','NRI'),('4','Fixed'),('5','Demat')))
#     ngo = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple,
#                                 choices=MRL_CHOICES)

bankingproject/bankingapp/views.py
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
# from .forms import Valueform

def home(request):
    return render(request,'home.html')
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1= request.POST.get('password')
        user=auth.authenticate(username=username,password=password1)
        if user is not None:
            auth.login(request, user)
            return render(request,'welcome.html')
        else:
            messages.info(request,"invalid data")
            return render(request,'login.html')
    return render(request,"login.html")

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password1 = request.POST.get('password')
        password2 = request.POST.get('password1')
        if password1==password2:
           if User.objects.filter(username=username).exists():
               messages.info(request,"Username Taken")
               return render(request,'register.html')
           else:
               user = User.objects.create_user(username=username,password=password1)
               user.save()
               return render(request,'login.html')
        else:
           messages.info(request, "password not matching")
           return render(request,'register.html')
    return render(request, "register.html")



def logout(request):
    auth.logout(request)
    return redirect('/')

def welcome(request):
    return render(request,'welcome.html')
def form(request):
    return render(request,'form.html')
# def Valueform(request):
#     context ={}
#     context['form']= Valueform()
#     return render(request, "form.html", context)

bankingproject/templates/form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<!--<form action = "" method = "post">-->
<!--	{% csrf_token %}-->
<!--	{{form }}-->

<!--</form>-->

<form method="post">
    {% csrf_token %}
  <label for="fname">First name:</label>
  <input type="text" id="fname" name="fname"><br>
  <label for="lname">Last name:</label>
  <input type="text" id="lname" name="lname"><br>
    <label for="dob">DOB :</label>
    <input type="date" name="DOB" max="2030-31-12"><br>
    <label for="age">AGE :</label>
    <input type="number" name="Age"><br>
    <label for="gender">Gender :</label>
    <input type="radio" name="gender" value="male">Male
    <input type="radio" name="gender" value="fmale">Female
    <input type="radio" name="gender" value="other">Other<br>
  <label for="number">Number :</label>
    <input type="number" name="Number"><br>
  <label for="mail">Email :</label>
    <input type="email" name="email"><br>
  <label>
          Address :
          <br />
          <textarea name="address" cols="30" rows="3"></textarea>
  </label><br>
  <label for="district">District :</label>
  <select name = "dropdown">
    <option value = "Trivandrum" selected>Trivandrum</option>
    <option value = "Kollam">Kollam</option>
    <option value = "Pathanamthitta" required>Pathanamthitta</option>
    <option value = "Alappuzha" disabled>Alappuzha</option>
    <option value = "Kottayam">Kottayam</option>
    <option value = "Idukki">Idukki</option>
    <option value = "Ernakulam">Ernakulam</option>
    <option value = "Thrissur">Thrissur</option>
    <option value = "Palakkad">Palakkad</option>
    <option value = "Malappuram">Malappuram</option>
    <option value = "Kozhikkode">Kozhikkode</option>
    <option value = "Wayanad">Wayanad</option>
    <option value = "Kannur">Kannur</option>
    <option value = "Kasargod">Kasargod</option>
 </select><br>
  <label for="branches">Branches :</label>
  <select name = "dropdownlist">
    <option value = "Padmanabhapuram" selected>Padmanabhapuram</option>
    <option value = "Shanmugham">Shanmugham</option>
    <option value = "Krishnapuram" required>Krishnapuram</option>
    <option value = "Thangasheri" disabled>Thangasheri</option>
    <option value = "Adoor">Adoor</option>
    <option value = "Cherthala">Cherthala</option>
    <option value = "Munnar">Munnar</option>
    <option value = "Aluva">Aluva</option>
    <option value = "Edappally">Edappally</option>
    <option value = "Guruvayur">Guruvayur</option>
    <option value = "Tirur">Tirur</option>
    <option value = "Manjeri">Manjeri</option>
    <option value = "Mananchira">Mananchira</option>
    <option value = "Thamarasseri">Thamarasseri</option>
    <option value = "Kalpetta">Kalpetta</option>
    <option value = "Mananthavady">Mananthavady</option>
    <option value = "Thalassery">Thalassery</option>
    <option value = "Koothuparamba">Koothuparamba</option>
    <option value = "Manjesuaram">Manjesuaram</option>
 </select><br>
   <label for="Account">Account :</label>
  <select name = "dropdowna">
    <option value = "Saving" selected>Saving</option>
    <option value = "Current">Current</option>
    <option value = "NRI" required>NRI</option>
    <option value = "Fixed" required>Fixed</option>
    <option value = "Demat" required>Demat</option>
 </select><br>
  <input type="checkbox" name="debit" value="debit">Debit Card
   <br>
   <input type="checkbox" name="credit" value="credit">Credit Card
   <br>
   <input type="checkbox" name="chequebook" value="chequebook">Cheque Book
   <br>
    <input type="submit" value=Submit">
    <input type="button" value="logout">
</body>
</html>

bankingproject/templates/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<title>Creative Colorlib SignUp Form</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
<!-- Custom Theme files -->
<link href="{% static 'css/style1.css' %}" rel="stylesheet" type="text/css" media="all" />
<!-- //Custom Theme files -->
<!-- web font -->
<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
<!-- //web font -->
    </head>
{% include 'navbar.html' %}
{% block body %}
 <div class="container px-4 text-center">
     <h1 class="fw-bolder">Welcome to CICIC</h1>
     <p class="lead">We Help you to Grow </p>
     <a class="btn btn-lg btn-light" href="{% url 'bankingapp:login' %}">Start</a>
 </div>
{% endblock %}





bankingproject/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
</head>
<style>
    body{
    padding:200px;
    text-align:center;
    background-image:url( "{% static 'backg.jpg' %}" );
    background-size:cover;
    }

 </style>
<body>
<form method="post">
    {% csrf_token %}
      <input type="text" name="username" placeholder="Enter your username"><br><br>
      <input type="password" name="password" placeholder="Enter password"><br><br>
      <input class="btn btn-primary" type="submit" value="Submit">
    <a class="btn btn-primary" href="{% url 'bankingapp:register' %}" role="button">Register</a>
</form>
    {% for msg in messages %}
    <h1 style="color:white;">{{msg}}</h1>
    {% endfor %}

</body>
</html>

bankingproject/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
<a class="navbar-brand" href="{% url 'bankingapp:home' %}">CICIC</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bankingapp:home' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bankingapp:login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'bankingapp:register' %}">Register</a>

      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Branches
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Malappuram">Malappuram</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kozhikode">Kozhikkode</a>
          <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Wayanad_district">Wayanad</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kannur">Kannur</a>
            <a class="dropdown-item" href="https://en.wikipedia.org/wiki/Kasaragod">Kasargode</a>
        </div>
      </li>
    </ul>
  </div>
</nav>

bankingproject/templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Registration</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">

</head>
<style>
    body{
    padding:60px;
    text-align:center;
    background-image:url( "{% static 'background1.jpg' %}" );
    background-size:cover;
    }

 </style>
<body>
<h1>Register Here</h1>
<form action="" method="post">
    {% csrf_token %}
      <input type="text" name="username" placeholder="Enter your username"><br><br>
      <input type="password" name="password" placeholder="Enter password"><br><br>
      <input type="password" name="password1" placeholder="confirm password"><br><br>
      <input class="btn btn-primary" type="submit" value="Submit">
    </form>
    {% for msg in messages %}
    <h1 style="color:white;">{{msg}}</h1>
    {% endfor %}


</body>
</html>

bankingproject/templates/user_registration.html
{% extends 'core/base.html' %}

{% block head_title %}Banking System{% endblock %}

{% block content %}
{% if registration_form.non_field_errors %}
    {% for error in registration_form.non_field_errors %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
        <p class="font-bold">Error!</p>
        <p class="block sm:inline">{{ error }}</p>
    </div>
    {% endfor %}
{% endif %}
{% if address_form.non_field_errors %}
    {% for error in address_form.non_field_errors %}
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative mt-2" role="alert">
        <p class="font-bold">Error!</p>
        <p class="block sm:inline">{{ error }}</p>
    </div>
    {% endfor %}
{% endif %}

<h1 class="font-mono font-bold text-3xl text-center pb-5 pt-10">Register</h1>
<hr />
<div class="w-full mt-10">
    <form method="post" class="bg-white shadow-md rounded px-8 pt-6 pb-8 mb-4">
        {% csrf_token %}
        {% for hidden_field in registration_form.hidden_fields %}
            {{ hidden_field.errors }}
            {{ hidden_field }}
        {% endfor %}
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.first_name.id_for_label }}">
                    {{ registration_form.first_name.label }}
                </label>
                {{ registration_form.first_name }}
                {% if registration_form.first_name.errors %}
                    {% for error in registration_form.first_name.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.last_name.id_for_label }}">
                    {{ registration_form.last_name.label }}
                </label>
                {{ registration_form.last_name }}
                {% if registration_form.last_name.errors %}
                    {% for error in registration_form.last_name.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.email.id_for_label }}">
                    {{ registration_form.email.label }}
                </label>
                {{ registration_form.email }}
                {% if registration_form.email.errors %}
                    {% for error in registration_form.email.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.account_type.id_for_label }}">
                    {{ registration_form.account_type.label }}
                </label>
                {{ registration_form.account_type }}
                {% if registration_form.account_type.errors %}
                    {% for error in registration_form.account_type.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.gender.id_for_label }}">
                    {{ registration_form.gender.label }}
                </label>
                {{ registration_form.gender }}
                {% if registration_form.gender.errors %}
                    {% for error in registration_form.gender.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.birth_date.id_for_label }}">
                    {{ registration_form.birth_date.label }}
                </label>
                {{ registration_form.birth_date }}
                {% if registration_form.birth_date.errors %}
                    {% for error in registration_form.birth_date.errors %}
                    <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.password1.id_for_label }}">
                    {{ registration_form.password1.label }}
                </label>
                {{ registration_form.password1 }}
                {% if registration_form.password1.errors %}
                    {% for error in registration_form.password1.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ registration_form.password2.id_for_label }}">
                    {{ registration_form.password2.label }}
                </label>
                {{ registration_form.password2 }}
                    {% if registration_form.password2.errors %}
                    {% for error in registration_form.password2.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>

        {% for hidden_field in address_form.hidden_fields %} {{ hidden_field.errors }} {{ hidden_field }} {% endfor %}
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.street_address.id_for_label }}">
                    {{ address_form.street_address.label }}
                </label>
                {{ address_form.street_address }}
                {% if address_form.street_address.errors %}
                    {% for error in address_form.street_address.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.city.id_for_label }}">
                    {{ address_form.city.label }}
                </label>
                {{ address_form.city }}
                {% if address_form.city.errors %}
                    {% for error in address_form.city.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="flex flex-wrap -mx-3 mb-6">
            <div class="w-full md:w-1/2 px-3 mb-6 md:mb-0">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.postal_code.id_for_label }}">
                    {{ address_form.postal_code.label }}
                </label>
                {{ address_form.postal_code }}
                {% if address_form.postal_code.errors %}
                    {% for error in address_form.postal_code.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
            <div class="w-full md:w-1/2 px-3">
                <label class="block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" for="{{ address_form.country.id_for_label }}">
                    {{ address_form.country.label }}
                </label>
                {{ address_form.country }}
                {% if address_form.country.errors %}
                    {% for error in address_form.country.errors %}
                        <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        <div class="flex items-center justify-between">
            <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                Register
            </button>
        </div>
    </form>
</div>
{% endblock %}

bankingproject/templates/welcome.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div class="container px-4 text-center">
     <h1 class="fw-bolder">Welcome to CICIC</h1>
     <p class="lead">Hello</p>
     <a class="btn btn-lg btn-light" href="{% url 'bankingapp:form' %}">Start</a>
 </div>
</body>
</html>